<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BuatIrsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('buat_irs')->insert([
            [
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => '3',
                'semester' => '1',
                'kelas' => 'A',
                'ruang' => 'E102',
                'status' => 'Wajib',
                'nama_dosen' => 'Dr.Eng. Adi Wibowo, S.Si., M.Kom.',
                'time_date' => 'Senin, 09:40: - 12:10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => '3',
                'semester' => '1',
                'kelas' => 'B',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Dr.Eng. Adi Wibowo, S.Si., M.Kom.',
                'time_date' => 'Selasa, 07:00: - 09:30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => '3',
                'semester' => '1',
                'kelas' => 'C',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Dr.Eng. Adi Wibowo, S.Si., M.Kom.',
                'time_date' => 'Senin, 13:00: - 15:30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => '3',
                'semester' => '1',
                'kelas' => 'D',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Dr.Eng. Adi Wibowo, S.Si., M.Kom.',
                'time_date' => 'Selasa, 09:40: - 12:10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => '3',
                'semester' => '1',
                'kelas' => 'E',
                'ruang' => 'E102',
                'status' => 'Wajib',
                'nama_dosen' => 'Dr.Eng. Adi Wibowo, S.Si., M.Kom.',
                'time_date' => 'Senin, 15:40: - 18:10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => '3',
                'semester' => '1',
                'kelas' => 'F',
                'ruang' => 'E102',
                'status' => 'Wajib',
                'nama_dosen' => 'Dr.Eng. Adi Wibowo, S.Si., M.Kom.',
                'time_date' => 'Rabu, 09:40: - 12:10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6104',
                'nama_mk' => 'Logika Informatika',
                'sks' => '3',
                'semester' => '1',
                'kelas' => 'A',
                'ruang' => 'E102',
                'status' => 'Wajib',
                'nama_dosen' => 'Dr. Sutikno, S.T., M.Cs.',
                'time_date' => 'Jumat, 09:40 - 12:10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => '4',
                'semester' => '1',
                'kelas' => 'A',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Nurdin Bahtiar, S.Si., M.T.',
                'time_date' => 'Rabu, 07:00 - 10:20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => '4',
                'semester' => '1',
                'kelas' => 'B',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Nurdin Bahtiar, S.Si., M.T.',
                'time_date' => 'Selasa, 13:00 - 16:20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => '4',
                'semester' => '1',
                'kelas' => 'C',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Nurdin Bahtiar, S.Si., M.T.',
                'time_date' => 'Rabu, 13:00 - 16:20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => '4',
                'semester' => '1',
                'kelas' => 'D',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Nurdin Bahtiar, S.Si., M.T.',
                'time_date' => 'Kamis, 13:00 - 16:20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => '4',
                'semester' => '1',
                'kelas' => 'E',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Nurdin Bahtiar, S.Si., M.T.',
                'time_date' => 'Jumat, 13:00 - 16:20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => '2',
                'semester' => '1',
                'kelas' => 'A',
                'ruang' => 'E102',
                'status' => 'Wajib',
                'nama_dosen' => 'Prof. Dr. Dra. Sunarsih M.Si.',
                'time_date' => 'Kamis, 07:00 - 08:40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => '2',
                'semester' => '1',
                'kelas' => 'B',
                'ruang' => 'K202',
                'status' => 'Wajib',
                'nama_dosen' => 'Prof. Dr. Dra. Sunarsih M.Si.',
                'time_date' => 'Senin, 16:30 - 18:10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => '2',
                'semester' => '1',
                'kelas' => 'C',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Prof. Dr. Dra. Sunarsih M.Si.',
                'time_date' => 'Selasa, 16:30 - 18:10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => '2',
                'semester' => '1',
                'kelas' => 'D',
                'ruang' => 'E103',
                'status' => 'Wajib',
                'nama_dosen' => 'Prof. Dr. Dra. Sunarsih M.Si.',
                'time_date' => 'Rabu, 10:30 - 12:10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => '2',
                'semester' => '1',
                'kelas' => 'E',
                'ruang' => 'E102',
                'status' => 'Wajib',
                'nama_dosen' => 'Prof. Dr. Dra. Sunarsih M.Si.',
                'time_date' => 'Rabu, 10:30 - 14:40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6103',
                'nama_mk' => 'Dasar Sistem',
                'sks' => '3',
                'semester' => '1',
                'kelas' => 'A',
                'ruang' => 'E201',
                'status' => 'Wajib',
                'nama_dosen' => 'Adhe Setya Pramayoga, M.T.',
                'time_date' => 'Kamis, 11:00 - 13:30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'UUW00003',
                'nama_mk' => 'Pancasila dan Kewarganegaraan',
                'sks' => '3',
                'semester' => '1',
                'kelas' => 'A',
                'ruang' => 'E101',
                'status' => 'Wajib',
                'nama_dosen' => 'Priyo Sidik Sasongko, S.Si., M.Kom.',
                'time_date' => 'Kamis, 14:00 - 16:30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'UUW00007',
                'nama_mk' => 'Bahasa Inggris',
                'sks' => '2',
                'semester' => '1',
                'kelas' => 'A',
                'ruang' => 'E201',
                'status' => 'Wajib',
                'nama_dosen' => 'Guruh Aryotejo, S.Kom., M.Sc.',
                'time_date' => 'Jumat, 07:00 - 08:50',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'UUW00005',
                'nama_mk' => 'Olah Raga',
                'sks' => '1',
                'semester' => '1',
                'kelas' => 'A',
                'ruang' => 'Lapangan Undip',
                'status' => 'Wajib',
                'nama_dosen' => 'Dr. Aris Puji Widodo, S.Si., M.T.',
                'time_date' => 'Jumat, 15:00, 15:50',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
