<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class IrsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('irs')->insert([
            [
                'nim' => '24060122199999',
                'jadwal_id' => '2',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '9',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '14',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '19',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '24',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '29',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '34',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '39',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '44',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '49',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '54',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '59',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122199999',
                'jadwal_id' => '64',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            //seed bintang syafrian rizal
            //semester 1
            [
                'nim' => '24060122120031',
                'jadwal_id' => '2',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '7',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '9',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '14',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '19',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '24',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '29',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '34',
                'semester' => '1',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //semester 2
            [
                'nim' => '24060122120031',
                'jadwal_id' => '38',
                'semester' => '2',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '39',
                'semester' => '2',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '40',
                'semester' => '2',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '41',
                'semester' => '2',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '42',
                'semester' => '2',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //semester 3
            [
                'nim' => '24060122120031',
                'jadwal_id' => '44',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '49',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '54',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '59',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '64',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '69',
                'semester' => '3',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //semester 4
            [
                'nim' => '24060122120031',
                'jadwal_id' => '73',
                'semester' => '4',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '74',
                'semester' => '4',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '75',
                'semester' => '4',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '76',
                'semester' => '4',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '77',
                'semester' => '4',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nim' => '24060122120031',
                'jadwal_id' => '78',
                'semester' => '4',
                'status' => 'baru',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
