<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JadwalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('jadwal')->insert([
            [
                'hari' => 'Senin',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:40',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'F',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E102',
                'kode_mk' => 'PAIK6104',
                'nama_mk' => 'Logika Informatika',
                'sks' => 3,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '07:00',
                'jam_selesai' => '08:40',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'K202',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'K202',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '11:00',
                'jam_selesai' => '13:30',
                'ruang' => 'E201',
                'kode_mk' => 'PAIK6103',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'kelas' => 'A',
                'kapasitas' => 35,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '14:00',
                'jam_selesai' => '16:30',
                'ruang' => 'E101',
                'kode_mk' => 'UUW00003',
                'nama_mk' => 'Pancasila dan Kewarganegaraan',
                'sks' => 3,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '07:00',
                'jam_selesai' => '08:50',
                'ruang' => 'E201',
                'kode_mk' => 'UUW00007',
                'nama_mk' => 'Bahasa Inggris',
                'sks' => 2,
                'kelas' => 'A',
                'kapasitas' => 25,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '15:00',
                'jam_selesai' => '15:50',
                'ruang' => 'Lapangan Undip',
                'kode_mk' => 'UUW00005',
                'nama_mk' => 'Olah Raga',
                'sks' => 1,
                'kelas' => 'A',
                'kapasitas' => 55,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
