<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JadwalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('jadwal')->insert([
            [
                //Jadwal Semester 1
                'hari' => 'Senin',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:40',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'F',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E102',
                'kode_mk' => 'PAIK6104',
                'nama_mk' => 'Logika Informatika',
                'sks' => 4,
                'semester' => 1,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'semester' => 1,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'semester' => 1,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'semester' => 1,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'semester' => 1,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'semester' => 1,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '07:00',
                'jam_selesai' => '08:40',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'K202',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '10:30',
                'jam_selesai' => '12:10',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '14:40',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'semester' => 1,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '15:50',
                'jam_selesai' => '17:30',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'E103',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '13:00',
                'jam_selesai' => '14:40',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'K202',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '09:40',
                'jam_selesai' => '11:20',
                'ruang' => 'K202',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'semester' => 1,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '10:50',
                'jam_selesai' => '11:40',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '11:50',
                'jam_selesai' => '12:40',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '10:40',
                'jam_selesai' => '11:30',
                'ruang' => 'B101',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '09:50',
                'jam_selesai' => '10:40',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '15:50',
                'jam_selesai' => '16:40',
                'ruang' => 'A304',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'E103',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '09:40',
                'jam_selesai' => '11:20',
                'ruang' => 'E103',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '10:30',
                'jam_selesai' => '12:10',
                'ruang' => 'K102',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '09:40',
                'jam_selesai' => '11:20',
                'ruang' => 'K102',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '07:00',
                'jam_selesai' => '08:40',
                'ruang' => 'E103',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'semester' => 1,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Jadwal Semester 3
            [
                'hari' => 'Senin',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6301',
                'nama_mk' => 'Struktur Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6301',
                'nama_mk' => 'Struktur Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6301',
                'nama_mk' => 'Struktur Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6301',
                'nama_mk' => 'Struktur Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6301',
                'nama_mk' => 'Struktur Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'E',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6304',
                'nama_mk' => 'Metode Numerik',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6304',
                'nama_mk' => 'Metode Numerik',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6304',
                'nama_mk' => 'Metode Numerik',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6304',
                'nama_mk' => 'Metode Numerik',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6304',
                'nama_mk' => 'Metode Numerik',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'E',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6302',
                'nama_mk' => 'Sistem Operasi',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Kimia',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6302',
                'nama_mk' => 'Sistem Operasi',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'E103',
                'kode_mk' => 'PAIK6302',
                'nama_mk' => 'Sistem Operasi',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6302',
                'nama_mk' => 'Sistem Operasi',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6302',
                'nama_mk' => 'Sistem Operasi',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'E',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6305',
                'nama_mk' => 'Interaksi Manusia dan Komputer',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6305',
                'nama_mk' => 'Interaksi Manusia dan Komputer',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6305',
                'nama_mk' => 'Interaksi Manusia dan Komputer',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6305',
                'nama_mk' => 'Interaksi Manusia dan Komputer',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6305',
                'nama_mk' => 'Interaksi Manusia dan Komputer',
                'sks' => 3,
                'semester' => 3,
                'kelas' => 'E',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6303',
                'nama_mk' => 'Basis Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'A',
                'kapasitas' => 47,
                'status' => 'Disetujui',
                'prodi' => 'Fisika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6303',
                'nama_mk' => 'Basis Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Matematika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6303',
                'nama_mk' => 'Basis Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Matematika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6303',
                'nama_mk' => 'Basis Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Matematika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6303',
                'nama_mk' => 'Basis Data',
                'sks' => 4,
                'semester' => 3,
                'kelas' => 'E',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Matematika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '10:30',
                'jam_selesai' => '12:10',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6306',
                'nama_mk' => 'Statistika',
                'sks' => 2,
                'semester' => 3,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Matematika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '10:30',
                'jam_selesai' => '12:10',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6306',
                'nama_mk' => 'Statistika',
                'sks' => 2,
                'semester' => 3,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Matematika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6306',
                'nama_mk' => 'Statistika',
                'sks' => 2,
                'semester' => 3,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Biologi',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '10:30',
                'jam_selesai' => '12:10',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6306',
                'nama_mk' => 'Statistika',
                'sks' => 2,
                'semester' => 3,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Biologi',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'K102',
                'kode_mk' => 'PAIK6306',
                'nama_mk' => 'Statistika',
                'sks' => 2,
                'semester' => 3,
                'kelas' => 'E',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Biologi',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Jadwal Semester 5
            [
                'hari' => 'Kamis',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6503',
                'nama_mk' => 'Sistem Informasi',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Biologi',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6503',
                'nama_mk' => 'Sistem Informasi',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6503',
                'nama_mk' => 'Sistem Informasi',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6503',
                'nama_mk' => 'Sistem Informasi',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'E101',
                'kode_mk' => 'UUW00008',
                'nama_mk' => 'Kewirausahaan',
                'sks' => 2,
                'semester' => 5,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '10:30',
                'jam_selesai' => '12:10',
                'ruang' => 'E101',
                'kode_mk' => 'UUW00008',
                'nama_mk' => 'Kewirausahaan',
                'sks' => 2,
                'semester' => 5,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '10:30',
                'jam_selesai' => '12:10',
                'ruang' => 'E101',
                'kode_mk' => 'UUW00008',
                'nama_mk' => 'Kewirausahaan',
                'sks' => 2,
                'semester' => 5,
                'kelas' => 'C',
                'kapasitas' => 51,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'E101',
                'kode_mk' => 'UUW00008',
                'nama_mk' => 'Kewirausahaan',
                'sks' => 2,
                'semester' => 5,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6504',
                'nama_mk' => 'Proyek Perangkat Lunak',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'K202',
                'kode_mk' => 'PAIK6504',
                'nama_mk' => 'Proyek Perangkat Lunak',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6504',
                'nama_mk' => 'Proyek Perangkat Lunak',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6504',
                'nama_mk' => 'Proyek Perangkat Lunak',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6506',
                'nama_mk' => 'Keamanan dan Jaminan Informasi',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6506',
                'nama_mk' => 'Keamanan dan Jaminan Informasi',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6506',
                'nama_mk' => 'Keamanan dan Jaminan Informasi',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6506',
                'nama_mk' => 'Keamanan dan Jaminan Informasi',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6501',
                'nama_mk' => 'Pengembangan Berbasis Platform',
                'sks' => 4,
                'semester' => 5,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6501',
                'nama_mk' => 'Pengembangan Berbasis Platform',
                'sks' => 4,
                'semester' => 5,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Statistika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6501',
                'nama_mk' => 'Pengembangan Berbasis Platform',
                'sks' => 4,
                'semester' => 5,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6501',
                'nama_mk' => 'Pengembangan Berbasis Platform',
                'sks' => 4,
                'semester' => 5,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6502',
                'nama_mk' => 'Komputasi Tersebar dan Paralel',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6502',
                'nama_mk' => 'Komputasi Tersebar dan Paralel',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6502',
                'nama_mk' => 'Komputasi Tersebar dan Paralel',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6502',
                'nama_mk' => 'Komputasi Tersebar dan Paralel',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6505',
                'nama_mk' => 'Pembelajaran Mesin',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'E102',
                'kode_mk' => 'PAIK6505',
                'nama_mk' => 'Pembelajaran Mesin',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'B',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'A303',
                'kode_mk' => 'PAIK6505',
                'nama_mk' => 'Pembelajaran Mesin',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'C',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E101',
                'kode_mk' => 'PAIK6505',
                'nama_mk' => 'Pembelajaran Mesin',
                'sks' => 3,
                'semester' => 5,
                'kelas' => 'D',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
