<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JadwalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('jadwal')->insert([
            [
                'hari' => 'Senin',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:40',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'kelas' => 'F',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E102',
                'kode_mk' => 'PAIK6104',
                'nama_mk' => 'Logika Informatika',
                'sks' => 3,
                'kelas' => 'A',
                'kapasitas' => 50,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '07:00',
                'jam_selesai' => '10:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '13:00',
                'jam_selesai' => '16:20',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624103',
                'nama_mk' => 'Struktur Diskret',
                'sks' => 4,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '07:00',
                'jam_selesai' => '08:40',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'K202',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '10:30',
                'jam_selesai' => '12:10',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '13:00',
                'jam_selesai' => '14:40',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624104',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '15:40',
                'jam_selesai' => '18:10',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '09:40',
                'jam_selesai' => '12:10',
                'ruang' => 'E103',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '13:00',
                'jam_selesai' => '15:30',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '07:00',
                'jam_selesai' => '09:30',
                'ruang' => 'E102',
                'kode_mk' => 'MIK1624101',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '15:50',
                'jam_selesai' => '17:30',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'E103',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '13:00',
                'jam_selesai' => '14:40',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Selasa',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'K202',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '09:40',
                'jam_selesai' => '11:20',
                'ruang' => 'K202',
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '10:50',
                'jam_selesai' => '11:40',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '11:50',
                'jam_selesai' => '12:40',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '10:40',
                'jam_selesai' => '11:30',
                'ruang' => 'B101',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '09:50',
                'jam_selesai' => '10:40',
                'ruang' => 'E102',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '15:50',
                'jam_selesai' => '16:40',
                'ruang' => 'A304',
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Rabu',
                'jam_mulai' => '16:30',
                'jam_selesai' => '18:10',
                'ruang' => 'E103',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'kelas' => 'A',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Kamis',
                'jam_mulai' => '09:40',
                'jam_selesai' => '11:20',
                'ruang' => 'E103',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'kelas' => 'B',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Senin',
                'jam_mulai' => '10:30',
                'jam_selesai' => '12:10',
                'ruang' => 'K102',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'kelas' => 'C',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '09:40',
                'jam_selesai' => '11:20',
                'ruang' => 'K102',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'kelas' => 'D',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hari' => 'Jumat',
                'jam_mulai' => '07:00',
                'jam_selesai' => '08:40',
                'ruang' => 'E103',
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'kelas' => 'E',
                'kapasitas' => 45,
                'status' => 'Disetujui',
                'prodi' => 'Informatika',
                'sifat' => 'Wajib',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
