<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MataKuliahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('matakuliah')->insert([
            //Matakuliah semester 1
            [
                'kode_mk' => 'PAIK6102',
                'nama_mk' => 'Dasar Pemrograman',
                'sks' => 3,
                'semester' => '1',
                'status' => 'Wajib',
                'deskripsi' => 'Mata kuliah Dasar Pemrograman merupakan seri pertama kelompok pengembangan perangkat lunak dengan fokus pada paradigma fungsional yang dilengkapi dengan notasi fungsional.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6104',
                'nama_mk' => 'Logika Informatika',
                'sks' => 4,
                'semester' => '1',
                'status' => 'Wajib',
                'deskripsi' => 'Logika Informatika merupakan sebuah mata kuliah sebagai dasar bagi matakuliah lain seperti Sistem Cerdas, dengan harapan mahasiswa mempunyai konsep berpikir komputasi (Computational thinking) dalam memecahkan sebuah masalah. Mata kuliah ini berisi konsep dasar Proporsional Logic dan First Order Logic, Validitaa, Invaliditas, Inference Rule, Pohon Semantik, Logical Ekuivalen serta pembentukan normal form dan resolusi baik PL maupu FOL.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6105',
                'nama_mk' => 'Struktur Diskrit',
                'sks' => 4,
                'semester' => '1',
                'status' => 'Wajib',
                'deskripsi' => 'Struktur Diskrit merupakan materi dasar dalam Ilmu Komputer. Mata kuliah ini akan membekali mahasiswa tentang teori-teori dan konsep dasar dalam melakukan komputasi, selain itu materi ini juga akan melatih mahasiswa untuk berfikir secara analitis dan logis. Mata kuliah Struktur Diskrit ini berisi beberapa materi dasar komputasi yang meliputi teori himpunan, fungsi, matematika kombinatorik, teori graph dan pohon serta beberapa penerapannya dalam komputasi.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6101',
                'nama_mk' => 'Matematika I',
                'sks' => 2,
                'semester' => '1',
                'status' => 'Wajib',
                'deskripsi' => 'Memahami konsep kalkulus untuk menyelesaikan persoalan dengan berpikir analitis.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6103',
                'nama_mk' => 'Dasar Sistem',
                'sks' => 3,
                'semester' => '1',
                'status' => 'Wajib',
                'deskripsi' => 'Mata kuliah ini menjadi dasar pada bidang kajian infrastruktur sistem yang mengenalkan sistem digital sebagai dasar membangun sistem komputer, hingga pembahasan tentang gambaran dasar teknologi informasi mencakup sistem operasi, internet, dan web.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'UUW1624107',
                'nama_mk' => 'Bahasa Inggris I',
                'sks' => 1,
                'semester' => '1',
                'status' => 'Wajib',
                'deskripsi' => 'Bahasa Inggris sebagai bahasa internasional perlu dikuasai mahasiswa terutama untuk mempelajari materi kuliah dan literatur berbahasa Inggris. Dalam kuliah ini, mahasiswa belajar materi uji bahasa Inggris sebagai bahasa asing yang meliputi aspek mendengar, menganalisis struktur, membaca, dan menulis paragraf dalam bahasa Inggris. Aspek berbicara dipelajari secara terpadu dengan aspek - aspek lain.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'UUW1624002',
                'nama_mk' => 'Pancasila',
                'sks' => 2,
                'semester' => '1',
                'status' => 'Wajib',
                'deskripsi' => 'Mahasiswa belajar untuk menganalisis masalah kontekstual kewarganegaraan, mengembangkan sikap positif, dan menampilkan perilaku mendukung yang berkaitan dengan semangat kebangsaan, cinta tanah air, demokrasi berkeadaban dan kesadaran hukum.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'UUW1624004',
                'nama_mk' => 'Bahasa Indonesia',
                'sks' => 1,
                'semester' => '1',
                'status' => 'Wajib',
                'deskripsi' => 'Mata kuliah ini bertujuan untuk meningkatkan kemampuan berbahasa Indonesia mahasiswa agar mampu berkomunikasi secara efektif dan efisien dalam kehidupan sehari-hari dan di lingkungan akademik.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //Matakuliah semester 5
            [
                'kode_mk' => 'PAIK6503',
                'nama_mk' => 'Sistem Informasi',
                'sks' => 3,
                'semester' => '5',
                'status' => 'Wajib',
                'deskripsi' => 'Secara umum mata kuliah ini berisi tentang Pembangunan SI dalam lingkup organisasi dan cara berbisnis yang sebuah organisasi, dan cara berinteraksi dengan lingkungannya dengan dukungan teknologi informasi. Beberapa jenis infrastruktur dan aplikasi yang mendukung organisasi di dalam menjalankan bisnis serta berinteraksi dengan lingkungannya antara lain adalah business intelligence.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'UUW00008',
                'nama_mk' => 'Kewirausahaan',
                'sks' => 2,
                'semester' => '5',
                'status' => 'Wajib',
                'deskripsi' => 'Kewirausahaan adalah kemampuan kreatif dan inovatif yang dijadikan dasar, kiat, dan sumber daya untuk mencari peluang menuju sukses. Melalui proses kreatif dan inovatif akan tercipta sesuatu yang baru dan berbeda yang dapat dijadikan nilai tambah untuk mencapai keunggulan bersaing.  Mata kuliah Kewirausahaan dirancang membekali mahasiswa agar dapat mempunyai pengetahuan, jiwa kewirausahaan, dan mampu melakukan simulasi kewirausahaan. Melalui kuliah ini kepada mahasiswa akan diberikan pengetahuan serta pemahaman tentang pentingnya karakter dan semangat Kewirausahaan, mengkomunikasikan ide dan pemikirannya kepada orang lain, dan mampu secara mandiri atau bersama-sama menciptakan produk jasa maupun layanan yang mempunyai potensi untuk dijual.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6504',
                'nama_mk' => 'Proyek Perangkat Lunak',
                'sks' => 3,
                'semester' => '5',
                'status' => 'Wajib',
                'deskripsi' => 'Definisi perangkat lunak skala besar; berbagai masalah dalam pengembangan perangkat lunak skala besar dan solusinya; abstraksi; SW Pattern; code generator; pengenalan berbagai platform, framework, dan tools; konfigurasi P/L (konsep, tools, practices...); dilengkapi dengan studi kasus berupa proyek pembangunan P/L skala besar dengan mempraktekkan semua teori yang telah diberikan, atau berupa reverse engineering suatu perangkat lunak skala besar untuk mendapatkan modelnya.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6506',
                'nama_mk' => 'Keamanan dan Jaminan Informasi',
                'sks' => 3,
                'semester' => '5',
                'status' => 'Wajib',
                'deskripsi' => 'Kuliah keamanan jaringan mempelajari bagaimana jika suatu sistem saling terhubung dengan jaringan. Ancaman apa saja yang dapat muncul dalam suatu jaringan. Selain itu juga disinggung bagaimana menganalisa  keamanan suatu jaringan serta menerapkan tindakan pencegahan maupun penanganan terhadap terjadinya suatu serangan  1 2 3',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6501',
                'nama_mk' => 'Pengembangan Berbasis Platform',
                'sks' => 4,
                'semester' => '5',
                'status' => 'Wajib',
                'deskripsi' => 'Mata kuliah Pengembangan Berbasis Platform merupakan seri kelima kelompok pemrograman, yaitu setelah Pemrograman Berorientasi Objek. Pada semester V, mahasiswa belajar pemrograman Web dan aplikasi mobile. Mahasiswa belajar paradigma scripting *script sampai bahasa PHP/ASP dipadukan dengan penerapan basis data dan aplikasi pengembangan web mutakhir. Mahasiswa juga belajar membuat aplikasi mobile sederhana. Selain itu mahasiswa dikenalkan pada platform lain yaitu game dan industrial. Pemrograman aplikatif ini menjadi modal untuk pengerjaan proyek perangkat lunak maupun praktik kerja lapangan.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6502',
                'nama_mk' => 'Komputasi Tersebar dan Paralel',
                'sks' => 4,
                'semester' => '5',
                'status' => 'Wajib',
                'deskripsi' => 'Mata kuliah Kualitas Komputasi Tersebar dan Pararel menyajikan konsep dan penerapan Komputasi Tersebar dan Pararel',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_mk' => 'PAIK6505',
                'nama_mk' => 'Pembelajaran Mesin',
                'sks' => 3,
                'semester' => '5',
                'status' => 'Wajib',
                'deskripsi' => 'Seiring dengan semakin banyaknya berbagai aplikasi di berbagai domain (misalnya bioinformatics, computer vision, robotics, dan lain-lain) maka kita akan menyaksikan semakin banyak pula dijumpai data yang kompleks,  sehingga diperlukan sebuah cara untuk dapat menyajikan informasi dari data-data tersebut secara lebih efektif dan efisien. Bidang machine learning menawarkan beberapa teknik untuk (otomatis) menyimpulkan pola yang berguna dalam data, dan membuat prediksi dari data tersebut. Teknik-teknik yang akan dipelajari dalam mata kuliah ini terfokus ke dalam tiga metode, yakni supervised learning, unsupervised learning, dan reinforcement learning. Pada mata kuliah ini juga akan dijelaskan bagaimana teknik evaluasi untuk menilai kinerja dari ketiga metode tersebut. Kajian mengenai teknik untuk mengatasi permasalahan curse of  dimensionality serta ensemble learning menjadi bahasan akhir dari mata kuliah machine learning.',
                'kapasitas' => 300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
